// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGestaoCompras.Infrastructure.Data;

#nullable disable

namespace SistemaGestaoCompras.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312113858_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.Compra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AtivaParaRelatorio")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdMercado")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.ConviteGrupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdCriadoPorUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdGrupo")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ConvitesGrupo");
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdCriadoPorUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.GrupoUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdGrupo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Papel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdGrupo");

                    b.HasIndex("IdUsuario", "IdGrupo")
                        .IsUnique();

                    b.ToTable("GrupoUsuarios");
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.ItemCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCompra")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeProdutoSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("IdCompra");

                    b.ToTable("ItensCompra");
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.ItemLista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdListaDeCompras")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("QuantidadePlanejada")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("IdListaDeCompras");

                    b.ToTable("ItensListas");
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.ItemListaPadrao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdListaDeComprasPadrao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("QuantidadePlanejada")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("IdListaDeComprasPadrao");

                    b.ToTable("ItensListaPadrao");
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.ListaDeCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdGrupo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ListasDeCompra");
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.ListaDeCompraPadrao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ListasDeCompraPadrao");
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.Marca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.Mercado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mercados");
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.Orcamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario", "Ano", "Mes")
                        .IsUnique();

                    b.ToTable("Orcamentos");
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdCategoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdCriadoPorUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMarca")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.RegistroDePreco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdMercado")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("QuantidadeReferencia")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("IdProduto", "IdMercado", "DataRegistro")
                        .IsUnique();

                    b.ToTable("RegistrosDePreco");
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Plano")
                        .HasColumnType("int");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.Compra", b =>
                {
                    b.OwnsOne("SistemaGestaoCompras.Domain.ValueObjects.Dinheiro", "ValorTotal", b1 =>
                        {
                            b1.Property<Guid>("CompraId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("CompraId");

                            b1.ToTable("Compras");

                            b1.WithOwner()
                                .HasForeignKey("CompraId");
                        });

                    b.Navigation("ValorTotal")
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.GrupoUsuario", b =>
                {
                    b.HasOne("SistemaGestaoCompras.Domain.Entities.Grupo", null)
                        .WithMany("Membros")
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestaoCompras.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.ItemCompra", b =>
                {
                    b.HasOne("SistemaGestaoCompras.Domain.Entities.Compra", null)
                        .WithMany("Itens")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SistemaGestaoCompras.Domain.ValueObjects.Dinheiro", "PrecoUnitario", b1 =>
                        {
                            b1.Property<Guid>("ItemCompraId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("ItemCompraId");

                            b1.ToTable("ItensCompra");

                            b1.WithOwner()
                                .HasForeignKey("ItemCompraId");
                        });

                    b.OwnsOne("SistemaGestaoCompras.Domain.ValueObjects.UnidadeMedida", "Unidade", b1 =>
                        {
                            b1.Property<Guid>("ItemCompraId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("ItemCompraId");

                            b1.ToTable("ItensCompra");

                            b1.WithOwner()
                                .HasForeignKey("ItemCompraId");
                        });

                    b.Navigation("PrecoUnitario")
                        .IsRequired();

                    b.Navigation("Unidade")
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.ItemLista", b =>
                {
                    b.HasOne("SistemaGestaoCompras.Domain.Entities.ListaDeCompra", null)
                        .WithMany("Itens")
                        .HasForeignKey("IdListaDeCompras")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SistemaGestaoCompras.Domain.ValueObjects.UnidadeMedida", "Unidade", b1 =>
                        {
                            b1.Property<Guid>("ItemListaId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("ItemListaId");

                            b1.ToTable("ItensListas");

                            b1.WithOwner()
                                .HasForeignKey("ItemListaId");
                        });

                    b.Navigation("Unidade")
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.ItemListaPadrao", b =>
                {
                    b.HasOne("SistemaGestaoCompras.Domain.Entities.ListaDeCompraPadrao", null)
                        .WithMany("Itens")
                        .HasForeignKey("IdListaDeComprasPadrao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SistemaGestaoCompras.Domain.ValueObjects.UnidadeMedida", "Unidade", b1 =>
                        {
                            b1.Property<Guid>("ItemListaPadraoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("ItemListaPadraoId");

                            b1.ToTable("ItensListaPadrao");

                            b1.WithOwner()
                                .HasForeignKey("ItemListaPadraoId");
                        });

                    b.Navigation("Unidade")
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.Orcamento", b =>
                {
                    b.OwnsOne("SistemaGestaoCompras.Domain.ValueObjects.Dinheiro", "ValorPlanejado", b1 =>
                        {
                            b1.Property<Guid>("OrcamentoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("OrcamentoId");

                            b1.ToTable("Orcamentos");

                            b1.WithOwner()
                                .HasForeignKey("OrcamentoId");
                        });

                    b.Navigation("ValorPlanejado")
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.Produto", b =>
                {
                    b.OwnsOne("SistemaGestaoCompras.Domain.ValueObjects.UnidadeMedida", "UnidadeBase", b1 =>
                        {
                            b1.Property<Guid>("ProdutoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("ProdutoId");

                            b1.ToTable("Produtos");

                            b1.WithOwner()
                                .HasForeignKey("ProdutoId");
                        });

                    b.Navigation("UnidadeBase")
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.RegistroDePreco", b =>
                {
                    b.OwnsOne("SistemaGestaoCompras.Domain.ValueObjects.Dinheiro", "Preco", b1 =>
                        {
                            b1.Property<Guid>("RegistroDePrecoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("RegistroDePrecoId");

                            b1.ToTable("RegistrosDePreco");

                            b1.WithOwner()
                                .HasForeignKey("RegistroDePrecoId");
                        });

                    b.OwnsOne("SistemaGestaoCompras.Domain.ValueObjects.UnidadeMedida", "UnidadeReferencia", b1 =>
                        {
                            b1.Property<Guid>("RegistroDePrecoId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("RegistroDePrecoId");

                            b1.ToTable("RegistrosDePreco");

                            b1.WithOwner()
                                .HasForeignKey("RegistroDePrecoId");
                        });

                    b.Navigation("Preco")
                        .IsRequired();

                    b.Navigation("UnidadeReferencia")
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.Usuario", b =>
                {
                    b.OwnsOne("SistemaGestaoCompras.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("SistemaGestaoCompras.Domain.ValueObjects.Senha", "Senha", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Senha")
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.Compra", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.Grupo", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.ListaDeCompra", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("SistemaGestaoCompras.Domain.Entities.ListaDeCompraPadrao", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
